# Generated by Django 5.2.1 on 2025-06-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_id',
            field=models.CharField(max_length=50),
        ),
    ]
