# Generated by Django 5.2.1 on 2025-06-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_events_id_alter_events_eventid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
