# Generated by Django 5.2.1 on 2025-06-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_location_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_id',
            field=models.CharField(max_length=200),
        ),
    ]
