# Generated by Django 5.2.1 on 2025-06-02 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_unit_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='adminId',
            new_name='admin_id',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='atdId',
            new_name='atd_id',
        ),
        migrations.RenameField(
            model_name='attendancefile',
            old_name='fileId',
            new_name='file_id',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='eventId',
            new_name='event_id',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='locationId',
            new_name='location_id',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='unitId',
            new_name='unit_id',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='volunteerId',
            new_name='volunteer_id',
        ),
    ]
