# Generated by Django 5.2.1 on 2025-06-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_unit_unit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_id',
            field=models.CharField(max_length=50),
        ),
    ]
