# Generated by Django 5.2.1 on 2025-06-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_rename_adminid_admin_admin_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='new_personal_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='old_personal_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
