# Generated by Django 5.2.1 on 2025-06-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_admin_admin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancefile',
            name='file_id',
            field=models.CharField(max_length=200),
        ),
    ]
