# Generated by Django 5.2.1 on 2025-06-02 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_volunteer_phone_alter_attendancefile_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='atd_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='attendancefile',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.unit'),
            preserve_default=False,
        ),
    ]
