# Generated by Django 5.2.1 on 2025-06-02 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_attendance_atd_id_alter_attendancefile_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancefile',
            old_name='enent',
            new_name='event',
        ),
    ]
