# Generated by Django 5.2.1 on 2025-06-03 06:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_rename_enent_attendancefile_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=250)),
                ('otp', models.CharField(blank=True, max_length=10, null=True)),
                ('user_type', models.CharField(default='unit', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='unit',
            name='plain_password',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
