# Generated by Django 5.2.1 on 2025-06-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_register_unit_plain_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='user_type',
            field=models.CharField(default='unit', max_length=50, null=True),
        ),
    ]
