# Generated by Django 5.2.1 on 2025-06-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_register_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='user_type',
            field=models.CharField(default='admin', max_length=20, null=True),
        ),
    ]
