# Generated by Django 5.2.1 on 2025-06-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_admin_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='location',
        ),
        migrations.AddField(
            model_name='events',
            name='location',
            field=models.ManyToManyField(blank=True, related_name='events', to='management.location'),
        ),
    ]
