# Generated by Django 5.2.1 on 2025-06-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_remove_events_location_events_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='events',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
