# Generated by Django 5.2.1 on 2025-06-03 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_rename_date_events_start_date_events_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.unit'),
        ),
    ]
